Feat/314add group
privacy-scaling-explorations/bandada pull request #317
Opened 2023-10-10 23:47 UTC by aguzmant103

## Description

This feature fixes #314  by adding a "Copy group ID" button that copies the group ID.

## Related Issue

## Does this introduce a breaking change?

-   [ ] Yes
-   [ x ] No

## Other information

2023-10-16 17:16 UTC, aguzmant103 commented
@vplasencia lmk what you think with this change now

2023-10-16 18:03 UTC, vplasencia requested changes

2023-10-16 19:48 UTC, aguzmant103 commented on apps/dashboard/src/pages/group.tsx
> +    const { hasCopied: hasCopied2, onCopy: onCopy2 } = useClipboard(
Oh yeah much more readable 😅

2023-10-16 19:50 UTC, aguzmant103 commented on apps/dashboard/src/pages/group.tsx
> +        groupId as string
@vplasencia didn't think of that, much safer!

2023-10-17 10:39 UTC, vplasencia approved these changes
Great work 👌

2023-10-17 10:39 UTC, merged